- name: Lancer le conteneur PrestaShop
  community.docker.docker_container:
    name: prestashop
    image: "prestashop/prestashop:{{ ps_version }}"
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
    env_file: "{{ ps_config_dir }}/prestashop.env"
    volumes:
      - "{{ ps_data_dir }}:/var/www/html"
